services:
  - type: web
    name: record-book-frontend
    runtime: node
    buildCommand: npm run build
    startCommand: npm run preview
    buildFilter: []
    envVars:
      - key: NODE_VERSION
        value: 18
    staticPublishPath: dist
